server:
  port: 8021
  address: 127.0.0.1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/organizationsmanage?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: judy
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      ## QQ邮箱配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: aa1040984760@163.com #发送邮件的邮箱地址
    password: RHCHZKYTAJJBDFWF #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    from: aa1040984760@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
